### PR TITLE
[FIX] Exclude tests module from packages to build.

### LINKED ISSUE #46: Exclude tests from packages list in setup.py
## Current behavior
Currently,  there is a `__init__.py` file in the _tests_ directory which includes the _tests_ directory in the packages to build.
This is an issue as this limit the usage of a _tests_ directory for dependent packages. i.e. this will results in breaking the tests for most dependent packages.

## Proposed solution
1. Remove the `__init__.py` file in the _tests_ directory.
1. Exclude the _tests_ directory from the packages list.

## New behavior
Implementing the second solution would prevent breaking dependent packages without affecting the current behavior.

I'll open a PR with the second solution.

### PR DESCRIPTION
**Pull request by mathdugre**
This change is to fix #46.

### CODE REVIEW

**Comment by NickolausDS** [comment]
Thanks for the PR!

Since this package uses MANIFEST.in, it might be better to specify excludes there. Something like:
```
prune tests
prune examples
global-exclude .*
```

**Comment by mathdugre** [comment]
I'm not so familiar with the packaging procedure.
Should it only be included in MANIFEST.in? Or in both setup.py and MANIFEST.in?

**Comment by NickolausDS** [comment]
It would be best if it was only a single location. I'm not too familiar with the differences between passing args through `find_packages()` vs using a `MANIFEST.in` file, but the latter has worked pretty well and I would prefer to continue using it unless we have a good reason to switch.

**Comment by mathdugre** [comment]
Hi @NickolausDS , I made the requested changes. If there is nothing else, I think this would be ready to be merged.

**Comment by NickolausDS** [comment]
Thank you!

**Pull request merged**
